FROM php:7.4.25-cli-buster

RUN apt-get update && apt-get install -y \
        libcurl4-gnutls-dev \
        zlib1g-dev libicu-dev g++ \
        librabbitmq-dev \
        libzip-dev \
        zip \
        libpng-dev libjpeg62-turbo-dev \
    && pecl install amqp mongodb \
	&& docker-php-ext-install \
        zip \
        curl \
        bcmath \
        sockets \
        pdo_mysql \
        exif \
        calendar \
    && docker-php-ext-enable amqp \
        mongodb \
    && docker-php-ext-configure intl \
    && docker-php-ext-configure gd --with-jpeg \
    && docker-php-ext-install \
    	gd \
    	intl

RUN chown -R www-data:www-data /var/www

WORKDIR /var/www/site