FROM php:7.4.19-cli-buster

RUN apt update && apt install -y libpng-dev librabbitmq-dev && \
    docker-php-ext-install bcmath pdo_mysql sockets gd exif pcntl && \
    pecl install amqp && \
    docker-php-ext-enable amqp && \
    apt purge -y libpng-dev librabbitmq-dev

RUN chown -R www-data:www-data /var/www

WORKDIR /var/www/site